version: '3.8'

services:
  mailserver:
    image: greenmail/standalone:2.0.0
    container_name: greenmail
    ports:
      - "3025:3025"
      - "3110:3110"
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3110/api/service/ready"]
      interval: 5s
      timeout: 5s
      retries: 10